Repository Devmangrani/JobSewa, pull requests merged in 2024-10, with the labels that each got.

#50 Improved footer design
  components/Intro.jsx
Labels: hacktober-accepted, Hacktoberfest-2024

#56 Add FUNDING.yml
  .github/FUNDING.yml
Labels: hacktober-accepted, Hacktoberfest-2024

#61 Navbar and Organisation UI
  Utils/NgoData.js
  components.json
  components/NavBar.jsx
  components/NgoCard.jsx
  components/ui/avatar.jsx
  components/ui/badge.jsx
  components/ui/button.jsx
  components/ui/card.jsx
  lib/utils.js
  package-lock.json
  package.json
  pages/frontend/organizations.jsx
  styles/globals.css
  tailwind.config.js
Labels: hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#62 Login and Register Page UI fixed and made responsive.
  pages/_app.js
  pages/auth/login.jsx
  pages/auth/register.jsx
  public/login-hero.svg
  styles/Login.module.css
Labels: hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#59 changed webpage logo
  components/NavBar.jsx
  public/Jobsewa_logo.png
Labels: hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#64 Update Home Page
  components/Intro.jsx
  components/NavBar.jsx
  pages/frontend/displayJobs.jsx
  pages/frontend/organizations.jsx
  pages/frontend/postAJob.jsx
  pages/frontend/postedJob.jsx
  pages/index.js
Labels: hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#75 Enhancement: added UI changes on main page
  components/Intro.jsx
  components/NavBar.jsx
  components/NgoCard.jsx
  package-lock.json
  package.json
Labels: enhancement, hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#78 feat: add home navigation on the login/signup
  pages/auth/login.jsx
  pages/auth/register.jsx
  public/back-arrow.svg
  styles/Login.module.css
Labels: enhancement, hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#85 fix forget password bug
  pages/api/auth/forgetPassword.js
  pages/auth/forget-password.jsx
Labels: bug, hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#101 fix: button height for smaller devices
  pages/frontend/dashboard.jsx
Labels: enhancement, hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#104 NGOs added
  .env
  Utils/NgoData.js
  models/Job.js
  models/User.js
  package-lock.json
  package.json
  pages/api/auth/register.js
  pages/api/job/postAJob.js
  pages/auth/register.jsx
  pages/frontend/postAJob.jsx
  styles/Login.module.css
Labels: enhancement, hacktober-accepted, Hacktoberfest-2024, hacktoberfest

#105 fix: alignment of arrow in hamburger menu
  styles/Navbar.module.css
Labels: enhancement, hacktober-accepted, Hacktoberfest-2024, hacktoberfest
